version: '3.2'

services:
  database:
    image: mariadb:10.7.1-focal
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed

    volumes:
      - database:/var/lib/mysql
    secrets:
      - mysql_root_password
      - mysql_password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    app:
      image: nextcloud:20.0.14-fpm
      restart: always
      links:
        - database
      volumes:
        - nextcloud:/var/www/html
      environment:
        - MYSQL_ROOT_PASSWORD=/run/secrets/mysql_root_password
        - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
        - MYSQL_DATABASE=nextcloud
        - MYSQL_USER=nextcloud
    proxy:
      image: nginx:1.21.4
      restart: always
      ports:
        - 80:80
      links:
        - app
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - nextcloud:/var/www/html

volumes:
  database:
    nextcloud:

      secrets:
        mysql_root_password:
          file: ./mysql_root_password.txt
    mysql_password:
      file: ./mysql_password.txt
