version: '3.2'

services:
  database:
    image: mariadb:10.7.1-focal
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed
    volumes:
      - database:/var/lib/mysql
    secrets:
      - mysql_root_password
      - mysql_password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - backend

  redis:
    image: redis:6.2.6-alpine3.14
    restart: always
    networks:
      - backend

  app:
    image: nextcloud:22.2.3-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_ROOT_PASSWORD=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - REDIS_HOST=redis
      - OVERWRITEPROTOCOL=https
    depends_on:
      - database
      - redis
    networks:
      - backend

  web:
    build: web
    restart: always
    volumes:
      - nextcloud:/var/www/html
    env_file:
      - host.env
    depends_on:
      - app
    networks:
      - certs
      - backend

volumes:
  database:
  nextcloud:
  conf:
  certs:
  vhost:
  html:
  acme:

networks:
  backend:
  certs:
    name: certs
    external: true

secrets:
  mysql_root_password:
    file: ./mysql_root_password.txt
  mysql_password:
    file: ./mysql_password.txt
